### PR TITLE
feature: ci pipeline for npm publish

### LINKED ISSUE #26: NPM package
Is there an NPM package, I love how this looks, would love to try it.

### PR DESCRIPTION
**Pull request by shrynx**
ci pipeline for multiplatform build and npm publish.

### changes
- changes build configuration
- changes test configuration
- adds ci scripts for builds and npm release
- updates readme for new installation and usage

### closes 
#26 
#23 

### ci instruction
- setup azure account (duh !)
- to make an npm release for now it is setup using azure pipeline.
so setup a service connections to connect with npm and keep the name in sync with 
`customEndpoint` field in `azure-pipeline.yml` (currently set as `npm-publish-package`)

### test release
[@shriyans/ppx_bs_css](https://www.npmjs.com/package/@shriyans/ppx_bs_css)

### acknowledgement
used ci scripts and setup from [bs-log](https://github.com/minima-app/bs-log)

### CODE REVIEW

**Comment by astrada** [comment]
Thank you very much!

**Comment by shrynx** [comment]
thanks a lot building the ppx in the first place 🙂

**Comment by idkjs** [comment]
Do we need to update the readme or we going with `@shriyans/ppx_bs_css`

**Comment by shrynx** [comment]
@astrada Hi !
do you plan on publishing the package on npm ?
the setup should be smooth on azure.

**Comment by astrada** [comment]
Just published, thank you again (sorry for the delay :smile:)!

**Pull request merged**
